erDiagram
    macro_indicator {
        int id
        string type
        string name
        float value
        datetime date_time
        boolean is_leading_indicator
        string region
        datetime creation_data_time
    }
    