erDiagram
    macro_indicator {
        int id
        string type
        string indicator_name
        float value
        datetime date_time
        boolean is_leading_indicator
        datetime creation_data_time
    }
    